- type: job
  id: Captain
  name: job-name-captain
  description: job-description-captain
  playTimeTracker: JobCaptain
  requirements:
    #SS220 requirement begin
    # off
    # - !type:DepartmentTimeRequirement
    #   department: Engineering
    #   time: 14400 # 4 hours
    # - !type:DepartmentTimeRequirement
    #   department: Medical
    #   time: 14400 # 4 hours
    # - !type:DepartmentTimeRequirement
    #   department: Science
    #   time: 14400 # 4 hours
    # - !type:DepartmentTimeRequirement
    #   department: Security
    #   time: 14400 # 4 hours
    # off
    - !type:DepartmentTimeRequirement
      department: Command
      time: 288000 # SS220-RoleTime 2
    - !type:AgeRequirement
      requiredAge: 20
    - !type:SpeciesRequirement #SS220-jobbans begin
      inverted: true
      species:
      - Felinid #SS220-jobbans end
    #SS220 requirement end
  weight: 20
  startingGear: CaptainGear
  icon: "JobIconCaptain"
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  radioBold: true
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      - type: DefibrillatorSkill #SS220 LimitationRevive

- type: startingGear
  id: CaptainGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesSunglasses
    id: CaptainPDA
#    ears: ClothingHeadsetAltCommand #SS220-Law Department
  storage:
    back:
    - Flash
    # - StationCharter
