# Â© SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

- type: entityTable
  id: LockerFillClown
  table: !type:AllSelector
    children:
    - id: ClothingMaskClown
    - id: ClothingShoesClown
    - id: ClothingUniformJumpsuitClown
    - id: BikeHorn
    - id: ClothingBackpackSatchelClown
    - id: ClothingBackpackClown
    - id: ClothingBackpackDuffelClown
    - id: CrayonRainbow
    - id: ClownStampBox #ss220-fake-stump-update
    - id: ClownMimeCyborgInstruction #ss220-clownmimecyborg-update
    - !type:NestedSelector
      tableId: AllToyWeaponsBundleTable
      prob: 0.075
    - !type:NestedSelector
      tableId: AllFakeSyndieHardsuitsTable
      prob: 0.075


- type: entity
  id: LockerClownFilled
  suffix: Filled
  parent: LockerClown
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: LockerFillClown

- type: entity
  id: LockerMimeFilled
  suffix: Filled
  parent: LockerMime
  components:
  - type: StorageFill
    contents:
    - id: ClothingMaskMime
    - id: ClothingBackpackDuffelMime
    - id: ClothingBackpackMime
    - id: ClothingUniformJumpsuitMime
    - id: ClothingUniformJumpskirtMime
    - id: CrayonMime
    - id: ClownStampBox #ss220-fake-stump-update
    - id: ClownMimeCyborgInstruction #ss220-clownmimecyborg-update
