- type: job
  id: CentralCommandOfficial
  name: job-name-centcomoff
  description: job-description-centcomoff
  playTimeTracker: JobCentralCommandOfficial
  setPreference: false
  startingGear: CentcomGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-hos
  canBeAntag: false
  radioBold: true
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  # SS220 centcomm access fix begin
  - CentralCommandERT
  - CentralCommandBSO
  - CentralCommandCBURN
  # SS220 centcomm access fix end
  departmentsToIgnoreInTitles: # SS220 Round End Titles
  - Command                    # SS220 Round End Titles
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]
  #SS220 LimitationRevive - start
  - !type:AddComponentSpecial
    components:
    - type: DefibrillatorSkill
  #SS220 LimitationRevive - end

- type: startingGear
  id: CentcomGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomOfficial
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHatCentcom
    eyes: ClothingEyesGlassesSecurity #ss-220-GlassesSecurity
    gloves: ClothingHandsGlovesColorBlack
    outerClothing: ClothingOuterArmorBasic
    id: CentcomPDA
    ears: ClothingHeadsetAltCentCom
    belt: WeaponPistolN1984
    pocket1: BoxFolderBlack
    pocket2: CentCommNewPen #SS220-CentcomFashion
